[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true
env_shell_expand = false

[tools]
java = 'latest'
lua = "5.1"
go = "latest"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres" }
node = 'latest'
'npm:prettier' = 'latest'
'npm:@bitwarden/cli' = 'latest'
'npm:tldr' = 'latest'
'npm:@github/copilot-language-server' = 'latest'
'npm:httpyac' = 'latest'
fzf = 'latest'
kafka = 'latest'
python = "latest"
bat = 'latest'
glow = "latest"
hurl = 'latest'
lazygit = 'latest'
"go:github.com/jorgerojas26/lazysql" = { version = 'latest' }
maven = 'latest'
cmake = 'latest'
ripgrep = 'latest'
fd = 'latest'
pnpm = 'latest'
yarn = 'latest'
bottom = "latest"
chezmoi = 'latest'
delta = 'latest'
age = "latest"
golangci-lint-langserver = "latest"
golangci-lint = "latest"
rumdl = "latest"
yq = "latest"
rust = "stable"
eza = "latest"
xh = "latest"
uv = "latest"
"npm:@stoplight/prism-cli" = "latest"
#"npm:json-server" = "latest"
air = "latest"
sqlc = "latest"
gotestsum = "latest"
oapi-codegen = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:github.com/aarzilli/gdlv" = "latest"
zellij = "latest"
"cargo:bacon" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-audit" = "latest"
"cargo:cargo-expand" = "latest"
fx = "latest"
jnv = "latest"
marksman = "latest"
ollama = "latest"
"npm:@biomejs/biome" = "latest"
"npm:tsx" = "latest"
"npm:knip" = "latest"
tmux = "latest"
yazi = "latest"


[env]
_.path = ["~/hx/builds/current/bin"]
HELIX_RUNTIME="~/hx/builds/current/runtime"
