[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

[tools]
zellij = "latest"
lua = "5.1"
go = "latest"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "postgres" }
node = 'latest'
'npm:prettier' = 'latest'
'npm:@bitwarden/cli' = 'latest'
'npm:tldr' = 'latest'
fzf = 'latest'

